version: '2'
services:
  vacinacao-app:
    image: vacinacao
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://vacinacao-postgresql:5432/Vacinacao
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  vacinacao-postgresql:
    extends:
      file: postgresql.yml
      service: vacinacao-postgresql
